name: Build Windows EXE

on:
  push:
    tags:
      - 'v*.*.*' # build on tags like v1.0.0

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller qcodes

      - name: Locate QCoDeS configuration folder
        id: qcodes-config
        shell: pwsh
        run: |
          $cfg = python - << 'EOF'
import qcodes, os
print(os.path.join(os.path.dirname(qcodes.__file__), 'configuration'))
EOF
          Write-Host "Found QCoDeS config at: $cfg"
          "QCONFIG=$cfg" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build executable with PyInstaller
        shell: pwsh
        run: |
          pyinstaller `
            -i res/icons/AppIcon.png `
            --windowed `
            --onefile `
            --add-data "$Env:QCONFIG;qcodes/configuration" `
            keithleyControl.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/keithleyControl.exe
