
name: Build Windows EXE

on:
  push:
    tags:
      - 'v*.*.*' # build on tags like v1.0.0

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller `
            -i res/icons/AppIcon.png `
            --windowed `
            --onefile `
            --additional-hooks-dir .github/pyinstaller-hooks `
            keithleyControl.py
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/keithleyControl.exe
